# Generated by Django 3.1.5 on 2021-02-07 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('likes', '0002_auto_20210207_2254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='likecount',
            name='like_counts',
            field=models.IntegerField(default=0),
        ),
    ]
