# Generated by Django 3.1.5 on 2021-01-12 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_my_blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogtype',
            old_name='type',
            new_name='type_name',
        ),
    ]
