# Generated by Django 3.1.5 on 2021-01-16 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_my_blog', '0002_auto_20210112_1335'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ['-creat_time']},
        ),
    ]
