# Generated by Django 3.1.5 on 2021-02-10 16:15

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0005_auto_20210210_2201'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='more_info',
            new_name='Profile',
        ),
    ]
