# Generated by Django 3.1.5 on 2021-02-01 14:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0004_auto_20210201_2246'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='root',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='root_comment', to='comment.comment'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='parant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parant_comment', to='comment.comment'),
        ),
    ]
